//User management data
export const dummyUserData = [
    {
      userId: 'U001',
      userName: 'John Doe',
      phoneNumber: '123-456-7890',
      email: 'johndoe@example.com',
      address: '123 Elm Street, Springfield, IL',
      subscriptionPlan: 'Premium',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
      subscriptionPlan: 'Basic',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
      subscriptionPlan: 'Basic',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
      subscriptionPlan: 'Basic',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
      subscriptionPlan: 'Basic',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
      subscriptionPlan: 'Basic',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
      subscriptionPlan: 'Basic',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
      subscriptionPlan: 'Basic',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
      subscriptionPlan: 'Basic',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
      subscriptionPlan: 'Basic',
    },
  ]
// Agent Data
  export const dummyAgentData = [
    {
      userId: 'U001',
      userName: 'John Doe',
      phoneNumber: '123-456-7890',
      email: 'johndoe@example.com',
      address: '123 Elm Street, Springfield, IL',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
    },
    {
      userId: 'U002',
      userName: 'Jane Smith',
      phoneNumber: '987-654-3210',
      email: 'janesmith@example.com',
      address: '456 Oak Avenue, Boulder, CO',
    },
  ]

  //Expense management data
  export  const expenseData = [
    {
      userId: '1',
      regNumber: 'EXP123',
      date: '2024-12-01',
      detail: 'Purchase of raw materials',
      spend: 5000,
      profit: 1500,
    },
    {
      userId: '2',
      regNumber: 'EXP124',
      date: '2024-11-28',
      detail: 'Office supplies',
      spend: 300,
      profit: 100,
    },
    {
      userId: '3',
      regNumber: 'EXP125',
      date: '2024-11-25',
      detail: 'Employee salaries',
      spend: 20000,
      profit: -5000,
    },
    {
      userId: '4',
      regNumber: 'EXP126',
      date: '2024-11-20',
      detail: 'Utility bills',
      spend: 800,
      profit: 200,
    },
    {
      userId: '5',
      regNumber: 'EXP127',
      date: '2024-11-15',
      detail: 'Marketing campaigns',
      spend: 1200,
      profit: 400,
    },
  ];

  //instructional videos
  export const instructionalData = [
    {
      's.No': 1,
      image: 'https://via.placeholder.com/100',
      name: 'Safety Training',
      detail: 'Comprehensive safety protocols for tractor operation.',
      date: '2024-11-30',
      status: 'Active',
    },
    {
      's.No': 2,
      image: 'https://via.placeholder.com/100',
      name: 'Maintenance Guide',
      detail: 'Step-by-step instructions for daily maintenance.',
      date: '2024-12-01',
      status: 'Active',
    },
    {
      's.No': 3,
      image: 'https://via.placeholder.com/100',
      name: 'Operational Best Practices',
      detail: 'Guidelines to maximize efficiency and minimize wear.',
      date: '2024-12-02',
      status: 'Inactive',
    },
    {
      's.No': 4,
      image: 'https://via.placeholder.com/100',
      name: 'Emergency Procedures',
      detail: 'Quick actions for common emergencies.',
      date: '2024-12-03',
      status: 'Active',
    },
    {
      's.No': 5,
      image: 'https://via.placeholder.com/100',
      name: 'Advanced Features',
      detail: 'Tutorial on utilizing advanced features effectively.',
      date: '2024-12-04',
      status: 'Inactive',
    },
  ];

  // smart tractor kit data 

  export  const tractorKitData = [
    {
      deviceId: 'TK001',
      regNumber: 'REG12345',
      date: '2024-12-01',
      activationCode: 'ACT-001',
      subscriptionPlan: 'Basic',
    },
    {
      deviceId: 'TK002',
      regNumber: 'REG12346',
      date: '2024-11-28',
      activationCode: 'ACT-002',
      subscriptionPlan: 'Premium',
    },
    {
      deviceId: 'TK003',
      regNumber: 'REG12347',
      date: '2024-11-25',
      activationCode: 'ACT-003',
      subscriptionPlan: 'Standard',
    },
    {
      deviceId: 'TK004',
      regNumber: 'REG12348',
      date: '2024-11-20',
      activationCode: 'ACT-004',
      subscriptionPlan: 'Basic',
    },
    {
      deviceId: 'TK005',
      regNumber: 'REG12349',
      date: '2024-11-15',
      activationCode: 'ACT-005',
      subscriptionPlan: 'Premium',
    },
  ]

  //subscription data
  export const subscriptionData = [
    {
      's.No': 1,
      subscriptionName: 'Premium Plan',
      createdDate: '2024-12-01',
      detail: 'Access to all features and priority support',
      amount: '$99.99',
      status: 'Active',
    },
    {
      's.No': 2,
      subscriptionName: 'Standard Plan',
      createdDate: '2024-11-25',
      detail: 'Access to most features with limited support',
      amount: '$49.99',
      status: 'Inactive',
    },
    {
      's.No': 3,
      subscriptionName: 'Basic Plan',
      createdDate: '2024-11-20',
      detail: 'Access to basic features only',
      amount: '$19.99',
      status: 'Active',
    },
    {
      's.No': 4,
      subscriptionName: 'Enterprise Plan',
      createdDate: '2024-11-15',
      detail: 'Custom plan tailored for businesses',
      amount: '$499.99',
      status: 'Pending',
    },
    {
      's.No': 5,
      subscriptionName: 'Trial Plan',
      createdDate: '2024-12-10',
      detail: 'Free trial for 14 days',
      amount: '$0.00',
      status: 'Active',
    },
    {
      's.No': 6,
      subscriptionName: 'Trial Plan',
      createdDate: '2024-12-10',
      detail: 'Free trial for 14 days',
      amount: '$0.00',
      status: 'Active',
    },
  ];

  // add promotion data
  export  const promotionData = [
    {
      's.No': 1,
      image: 'https://via.placeholder.com/100',
      detail: '50% off on all items during Black Friday sale.',
      createdDate: '2024-12-01',
      expDate: '2024-12-31',
      status: 'Active',
    },
    {
      's.No': 2,
      image: 'https://via.placeholder.com/100',
      detail: 'Buy one, get one free on selected items.',
      createdDate: '2024-11-20',
      expDate: '2024-12-15',
      status: 'Expired',
    },
    {
      's.No': 3,
      image: 'https://via.placeholder.com/100',
      detail: 'Free shipping on orders above $50.',
      createdDate: '2024-11-10',
      expDate: '2024-12-01',
      status: 'Expired',
    },
    {
      's.No': 4,
      image: 'https://via.placeholder.com/100',
      detail: 'Holiday special discount: 20% off on electronics.',
      createdDate: '2024-12-10',
      expDate: '2025-01-10',
      status: 'Active',
    },
    {
      's.No': 5,
      image: 'https://via.placeholder.com/100',
      detail: 'End of season sale: Flat 30% off.',
      createdDate: '2024-12-05',
      expDate: '2024-12-20',
      status: 'Inactive',
    },
  ];